server:
  port: DEV_PORT

db:
  type: 'postgres'
  port: db_port
  database: db_name
  host: db_host
  username: db_username
  password: db_password
  synchronize: true
  ca: db_cert

jwt:
  expiresIn: 3600
  secret: 'sercret'

mailer:
  secure: true
  from: '"No Reply" <noreply@example.com>'
  host: ''
  user: ''
  pass: ''
