# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  # pull_request:
  #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Setup environment
        env:
          environment: dev
          DEV_PORT: 9000
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_CERT: ${{secrets.DB_CERT}}
        run: |
          cd ..
          git clone https://${{secrets.MY_GITHUB_TOKEN}}@github.com/famesensor/${{secrets.SECRET_REPOSITORY}}.git
      - run: npm run build --if-present
      - run: npm test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/Playgroud-NestJs-Document
            git pull origin develop
            npm ci
            npm run build
            pm2 restart Playgroud-NestJs-Document
